apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  namespace: your-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:{version}
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
    volumes:
    - name: config
      configMap:
        name: filebeat-config
